### ISSUE TITLE
Boot2Docker is deprecated in favor of Docker Toolbox

### ISSUE THREAD

**Issue by drissamri** [wercker/support#119]
How does the wercker CLI work with the new Docker toolbox?

Users-MBP:Server user$ wercker build
ERROR open /Users/user/.boot2docker/certs/boot2docker-vm/cert.pem: no such file or directory

**Comment by hatchan** [comment]
For now you need to get the docker environment variables from `docker-machine`. For the `default` machine use the following: 

```
eval $(docker-machine env default)
```

If you do not know the name of your machine use the following command to list all docker machines:

```
docker-machine ls
```

If you have not created a docker machine, use the following command to create a virtualbox docker machine:

```
docker-machine create --driver virtualbox default
```

**Comment by faiq** [comment]
@drissamri we just wrote an article about how to get started with docker-machine! check it out [here](http://devcenter.wercker.com/docs/using-the-cli/requirements.html)

**Comment by F21** [comment]
Maybe better UX can be achieved by letting the wercker cli call `docker-machine env dev` and parsing the results so that we don't have to add `eval "$(docker-machine env dev)" to `.profile`.

In addition, it would also make things on windows much easier as the default shells do not support `eval` and `export`.
