### ISSUE TITLE
Docker push tag environment variable no longer working

### ISSUE THREAD

**Issue by nhumrich** [wercker/support#141]
internal/docker-push used to respect environment-variables for the tag, but now it doesn’t.

     - internal/docker-push:
            repository: $REPO
            tag: $TAG
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
            ports: "80"
            entrypoint: "java -jar /app/service.jar"

This has worked in the past, as all my tags are in dockerhub. But recently this isn’t working, now it just pushes as "latest" probably because the $TAG is empty. I havent made any changes to my wercker.yml. I just went to docker pull my tag and noticed it wasnt there, and started to investigate.

**Comment by nhumrich** [comment]
Ok followup:

This works if I set the ENV VAR throught the targets env vars, but it doesnt work when I set it in the container. This somewhat makes sense to me, except I had it previously working.

I do a `git describe` to get the tag for a deploy and export it to an env-var so I can use it as the docker tag. I had this working a couple weeks ago, but not it doesnt work.

**Comment by hatchan** [comment]
After some discussion on slack it turns out that something in the base image might be causing this problem.

Normally exporting a value in a script step, or any other step, will be available when using as a property, even for `internal/` steps. Only exception is minimal distro's which do not have a compatible `env` command. See our devcenter for more information: http://devcenter.wercker.com/docs/faq/alpine-faq.html#i-receive-the-unable-to-sync-environment-when-using-docker-push-on-alpine
