### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by pgruenbacher** [wercker/support#218]
![image](https://cloud.githubusercontent.com/assets/3332598/15341018/30b536f8-1c5a-11e6-8288-4c566bd75acf.png)

Additional information:

Google-chrome-stable ubuntu

**Comment by pgruenbacher** [comment]
the dropdowns of the navbar were not working

**Comment by flenter** [comment]
Thank you for reporting! First of all: we should have an update ready soon that will prevent this error from happening in the future. 

Now out of curiosity: can you check which version of Chrome you are using? `Object.assign` is supported since Chrome 45 (latest stable version: 50). So this error shouldn't occur on the most recent versions of browsers.
