### ISSUE TITLE
syntax error when using wercker login command

### ISSUE THREAD

**Issue by mlennie** [wercker/support#54]
I created a question here: http://stackoverflow.com/questions/30917680/syntax-error-in-wercker-file-when-using-wercker-login-command

**Comment by jakirkham** [comment]
Are you using boot2docker?

**Comment by mlennie** [comment]
yes boot2docker through vagrant. It works if I don't run `docker ssh` first

**Comment by mies** [comment]
@mlennie could your run the following for us:

`wercker version` (to see if you're up to date)

and `wercker --debug login`
which should give more info

**Comment by jakirkham** [comment]
> It works if I don't run `docker ssh` first

You mean `vagrant ssh`, right?

Yes, so boot2docker is designed so that you do not need to go into the VM, which is what `vagrant ssh` does. All you need to do is run `boot2docker up` and set the environment variables to what it tells you to. If you have already initialized the VM, you may need to run `boot2docker init`. Now you can just use the `docker` command directly without entering the VM.

**Comment by mies** [comment]
also in what directory are you running the `wercker` command?

**Comment by mlennie** [comment]
Hello yes I meant `vagrant ssh`. And yes if I do not go into the vagrant VM then everything seems to work fine. Thank You. I am now having trouble using `wercker dev` and `wercker build`. I made an issue for that here: https://github.com/wercker/support/issues/57 If anyone could help me with that I'd appreciate it thanks.
