### ISSUE TITLE
BUG: Sometimes the store step fails

### ISSUE THREAD

**Issue by jakirkham** [wercker/support#62]
Not sure why this is the case or even how to reproduce it as it is sporadic. Also, don't have any more info as all it will say is it did fail.

**Comment by lindseybateman** [comment]
Thanks for reporting, we have seen it happen as well and are working on improving the overall stack.

**Comment by jakirkham** [comment]
Could I suggest that in the interim this not be treated as a failed build, but some other status? Particularly, if the tests passed and only storage failed.

**Comment by pimterry** [comment]
+1. This happens quite often for me, always fixes itself on a rebuild, but it's very annoying.

**Comment by hatchan** [comment]
We've implemented a couple of things, which should drastically minimize the store step failing. Please open a new ticket if it is still happening.

**Comment by jakirkham** [comment]
Thanks for your hard work on this.

**Comment by jakirkham** [comment]
Haven't seen any failures due to this issue in the last week. Very happy to see this improvement.

**Comment by pimterry** [comment]
I've just hit this again, for the first time since this fix (which is definitely a better rate than I used to get).

Failing build is at https://app.wercker.com/#buildstep/55df1abaa8e4929956040afd, and I've activated 'support', which I think think means you should be able to take a look at it.

It's an automated build triggered by a git commit from the prod deploy of the previous build. Only difference to the previous commit (which worked fine) is an incremented patch version number.
